# Playing Cards
# Standard deck encoding

chars = "ğŸ‚¡ğŸ‚¢ğŸ‚£ğŸ‚¤ğŸ‚¥ğŸ‚¦ğŸ‚§ğŸ‚¨ğŸ‚©ğŸ‚ªğŸ‚«ğŸ‚­ğŸ‚®ğŸ‚±ğŸ‚²ğŸ‚³ğŸ‚´ğŸ‚µğŸ‚¶ğŸ‚·ğŸ‚¸ğŸ‚¹ğŸ‚ºğŸ‚»ğŸ‚½ğŸ‚¾ğŸƒğŸƒ‚ğŸƒƒğŸƒ„ğŸƒ…ğŸƒ†ğŸƒ‡ğŸƒˆğŸƒ‰ğŸƒŠğŸƒ‹ğŸƒğŸƒğŸƒ‘ğŸƒ’ğŸƒ“ğŸƒ”ğŸƒ•ğŸƒ–ğŸƒ—ğŸƒ˜ğŸƒ™ğŸƒšğŸƒ›ğŸƒğŸƒ"
