# Alchemical Symbols
# Medieval/renaissance symbols

chars = "ğŸœ€ğŸœğŸœ‚ğŸœƒğŸœ„ğŸœ…ğŸœ†ğŸœ‡ğŸœˆğŸœ‰ğŸœŠğŸœ‹ğŸœŒğŸœğŸœğŸœğŸœğŸœ‘ğŸœ’ğŸœ“ğŸœ”ğŸœ•ğŸœ–ğŸœ—ğŸœ˜ğŸœ™ğŸœšğŸœ›ğŸœœğŸœğŸœğŸœŸğŸœ ğŸœ¡ğŸœ¢ğŸœ£ğŸœ¤ğŸœ¥ğŸœ¦ğŸœ§ğŸœ¨ğŸœ©ğŸœªğŸœ«ğŸœ¬ğŸœ­ğŸœ®ğŸœ¯ğŸœ°ğŸœ±ğŸœ²ğŸœ³ğŸœ´ğŸœµğŸœ¶ğŸœ·ğŸœ¸ğŸœ¹ğŸœºğŸœ»ğŸœ¼ğŸœ½ğŸœ¾ğŸœ¿ğŸ€ğŸğŸ‚ğŸƒğŸ„ğŸ…ğŸ†ğŸ‡ğŸˆğŸ‰ğŸŠğŸ‹ğŸŒğŸğŸğŸğŸğŸ‘ğŸ’ğŸ“ğŸ”ğŸ•ğŸ–ğŸ—ğŸ˜ğŸ™ğŸšğŸ›ğŸœğŸğŸğŸŸğŸ ğŸ¡ğŸ¢ğŸ£ğŸ¤ğŸ¥ğŸ¦ğŸ§ğŸ¨ğŸ©ğŸªğŸ«ğŸ¬ğŸ­ğŸ®ğŸ¯ğŸ°ğŸ±ğŸ²ğŸ³"
